### ISSUE TITLE
ShareDB Ace-editor bindings

### ISSUE THREAD

**Issue by jethrokuan** [share/sharedb-string-binding#1]
Hi,

I'm trying to bind shareDB to ace-editor, and realized there isn't a package out there yet, so I'm writing one. I have a couple of questions:

1. It seems that the way I should be doing this is through extending the text-diff-binding class. Is this correct?

2. I'm looking at this repo for some implementation details; what does `path` refer to is this repo?

**Comment by jethrokuan** [comment]
I've successfully integrated ace editor with shareDB, the code lives here: https://github.com/jethrokuan/sharedb-ace/

**Comment by curran** [comment]
Nice!

**Comment by cloudstrife94** [comment]
hi guys!
I tried to leverage this integration but I could find a link btw the sharedb implementation for textarea and this code !! does it really work for u ? if yes , can anyone post some sort of a clear tutorial for both server and client side code
